- name: Deploy AWS content
  hosts: aws
  become: true
  tasks:
    - apt: { name: nginx, state: present, update_cache: yes }
    - service: { name: nginx, enabled: yes, state: started }

    - name: Copy AWS page to both index files
      copy:
        src: "{{ playbook_dir }}/../index-aws.html"
        dest: "{{ item }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - /var/www/html/index.html
        - /var/www/html/index.nginx-debian.html

    - service: { name: nginx, state: reloaded }

    - name: Verify from Jenkins (public IP)
      uri:
        url: "http://{{ hostvars[inventory_hostname].ansible_host }}"
        return_content: yes
        status_code: 200
      register: page
      delegate_to: localhost

    - assert:
        that: "page.content is search('Welcome to AWS')"

# Deploy Azure content
- name: Deploy Azure content
  hosts: azure
  become: true
  tasks:
    - apt: { name: nginx, state: present, update_cache: yes }
    - service: { name: nginx, enabled: yes, state: started }

    - name: Copy Azure page to both index files
      copy:
        src: "{{ playbook_dir }}/../index-azure.html"
        dest: "{{ item }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - /var/www/html/index.html
        - /var/www/html/index.nginx-debian.html

    - service: { name: nginx, state: reloaded }

    - name: Verify from Jenkins (public IP)
      uri:
        url: "http://{{ hostvars[inventory_hostname].ansible_host }}"
        return_content: yes
        status_code: 200
      register: page
      delegate_to: localhost

    - assert:
        that: "page.content is search('Welcome to Azure')"
